name: kristen.laracuenta
favicon: null
layout_spectrum: 0.8160580380354077
typography_spectrum: 0.6305076731368899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4a134a'
    - '#bbd4f2'
    - '#70b0dc'
    - '#49426e'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
